version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=versanet.mysql.database.azure.com
      - MYSQL_USER=UserVersanetDb
      - MYSQL_PASSWORD=versanetdb$2024
      - MYSQL_DATABASE=versanetbd
      - MYSQL_PORT=3306
      - JWT_SECRET=mysecretkey
      - PORT=5000
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=465
      - MAIL_USER=yancarojas2003@gmail.com
      - MAIL_PASS=bokk vora jypi yxlh
      - MAIL_SECURE=true
      - MAIL_FROM=Versanet